services:
  v2ray:
    image: ghcr.io/v2fly/v2ray:v5.16.1
    restart: always
    networks:
      shadownet:
        ipv4_address: 172.20.0.20
    environment:
      - v2ray.vmess.aead.forced=false
    volumes:
      - ./v2ray.json:/etc/v2ray/config.json
    ports:
     - 2213

  caddy:
    image: caddy:2.8
    restart: always
    networks:
      shadownet:
        ipv4_address: 172.20.0.10
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/web/:/usr/share/caddy
      - ./caddy/data/:/data/caddy/
      - ./caddy/config/:/config/caddy
    ports:
      - 80:80
      - 443:443

networks:
  shadownet:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"